-- 0002_item_summary: the first line or two of an item's own text, for the dashboard's list.
--
-- The dashboard shows a handful of items at a time (FR-2.2), and a title alone often does not say
-- what an issue is about. The adapters store a short, whitespace-collapsed prefix of the body here
-- rather than the whole of it: the column exists to be rendered under a title in small type, and a
-- refresh that carried every issue body of eight repositories into the database would grow it by
-- orders of magnitude for text no page ever shows.
--
-- NULL is a normal value. It means the source has no body text for this item — a Todoist task, an
-- issue opened with an empty description, or a row written before this migration. Every read
-- COALESCEs it.
ALTER TABLE items ADD COLUMN summary TEXT;
