-- 0004_build_badge: the badge image for a repository's workflow, stored with the build it belongs
-- to.
--
-- The details page used to link the badge at its source and let the browser fetch it while the
-- page was being read (FR-2.3 AC5). That made the page's slowest part something this application
-- does not control: eight third-party requests on every load, which arrive late, can be rate
-- limited, and can be blocked outright by anything in the browser that filters other people's
-- images — and every one of those looks the same to the reader, like a build with no badge.
--
-- So the badge is fetched once, by the refresh run that fetched the build state it illustrates,
-- and stored here. The page then draws it from its own bytes and waits for nothing.
--
-- NULL is a normal value, and there are three ways to get one: a row written before this
-- migration, a run with no workflow file to address (GitHub's built-in Pages deployment), and a
-- badge fetch that failed — which is never allowed to fail a refresh, because a decorative image
-- is not worth a run.
ALTER TABLE builds ADD COLUMN badge BLOB;
